language: node_js
node_js: lts/*
script:
  - hexo generate
deploy:
  provider: script
  skip_cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  script:
    - hexo deploy
  on:
    branch: master
