# Menu
# The object key is the label and the value is the path.
menu:
  Home: /
  🗂️Archives: /archives

# The icons at the bottom of the page.
# The class value comes from font awesome.
#  Example: if the html code for the icon is <i class="fas fa-home"></i> the value for class will be fas fa-home.
footer_icons:
  "my GitHub":
    url: "https://github.com/ysfaran/"
    class: "fab fa-github"
  "my twitter":
    url: "https://twitter.com/ysfaran15"
    class: "fab fa-twitter"
  "contact me":
    url: "mailto:yusuf.aran@outlook.de"
    class: "fas fa-envelope"

# This is reserved for meta tags.
# List of supported items:
# 1. Twitter card image. See: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary.html
# 2. Open graph image. See: http://ogp.me/
meta:
  twitter:
    featured_image: img/default.jpg
  open_graph: #Facebook
    featured_image: img/default.jpg

# The sidebar is reserved for a twitter feed and blocks of text/html.
sidebar:
  twitter:
    enabled: true
    username: "ysfaran15"
    height: 800
  tldr:
    - block1:
      title: "I'm Yusuf Aran,"
      content: "not more than a passionate developer. See the footer for information about my person or to contact me!"

# If featured_image is missing from a post, this one will be used.
featured_image: ./img/default.jpg
